INSERT INTO Finance.charts (AccountCode, Account, Type) VALUES
-- Assets
(1000, 'Cash on Hand', 'Asset'),
(1010, 'Cash in Bank - Checking', 'Asset'),
(1020, 'Cash in Bank - Savings', 'Asset'),
(1030, 'Petty Cash', 'Asset'),
(1100, 'Accounts Receivable', 'Asset'),
(1110, 'Allowance for Doubtful Accounts', 'Asset'),
(1200, 'Prepaid Expenses', 'Asset'),
(1210, 'Prepaid Insurance', 'Asset'),
(1220, 'Prepaid Rent', 'Asset'),
(1300, 'Office Supplies', 'Asset'),
(1400, 'Equipment', 'Asset'),
(1410, 'Accumulated Depreciation - Equipment', 'Asset'),
(1500, 'Furniture & Fixtures', 'Asset'),
(1510, 'Accumulated Depreciation - Furniture', 'Asset'),
(1600, 'Vehicles', 'Asset'),
(1610, 'Accumulated Depreciation - Vehicles', 'Asset'),
-- Liabilities
(2000, 'Accounts Payable', 'Liability'),
(2010, 'Accrued Expenses', 'Liability'),
(2020, 'Accrued Salaries', 'Liability'),
(2030, 'Accrued Interest', 'Liability'),
(2100, 'VAT Payable', 'Liability'),
(2110, 'Income Tax Payable', 'Liability'),
(2120, 'Withholding Tax Payable', 'Liability'),
(2200, 'Short Term Loans', 'Liability'),
(2300, 'Long Term Loans', 'Liability'),
(2310, 'Mortgage Payable', 'Liability'),
(2400, 'Unearned Revenue', 'Liability'),
-- Equity
(3000, 'Owner''s Capital', 'Equity'),
(3010, 'Owner''s Drawing', 'Equity'),
(3100, 'Retained Earnings', 'Equity'),
-- Revenue
(4000, 'Service Revenue', 'Revenue'),
(4010, 'Consulting Revenue', 'Revenue'),
(4020, 'Professional Fees', 'Revenue'),
(4030, 'Interest Income', 'Revenue'),
(4040, 'Rental Income', 'Revenue'),
(4050, 'Other Income', 'Revenue'),
(4060, 'Sale Revenue', 'Revenue'),
-- Expenses
(6000, 'Salaries & Wages', 'Expense'),
(6010, 'Employee Benefits', 'Expense'),
(6020, 'SSS/PhilHealth/Pag-IBIG', 'Expense'),
(6100, 'Rent Expense', 'Expense'),
(6110, 'Utilities Expense', 'Expense'),
(6120, 'Internet & Phone Expense', 'Expense'),
(6200, 'Office Supplies Expense', 'Expense'),
(6210, 'Printing & Stationery', 'Expense'),
(6300, 'Depreciation Expense', 'Expense'),
(6400, 'Insurance Expense', 'Expense'),
(6500, 'Repairs & Maintenance', 'Expense'),
(6600, 'Advertising & Marketing', 'Expense'),
(6700, 'Transportation Expense', 'Expense'),
(6800, 'Professional Fees', 'Expense'),
(6810, 'Accounting Fees', 'Expense'),
(6820, 'Legal Fees', 'Expense'),
(6900, 'Bank Charges', 'Expense'),
(6910, 'Interest Expense', 'Expense'),
(7000, 'Bad Debts Expense', 'Expense'),
(7100, 'Taxes & Licenses', 'Expense'),
(7200, 'Miscellaneous Expense', 'Expense');